# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc04ff16153cee67c2a27050d1b6e30526046e460e78de950dcb6608de6639d7d10b3b3c59a0e28b49a30f379ef3c05d80287154c501e5949054bfa28f9465e

test:
  secret_key_base: b0f840cf7085d51b720fcfb2522b300ba08e196fdb256abb1edd3751a8dabe881d8c2c2e6ce3ca59a61d0019f947d0ad7c681ebd510f9840b0e4d1d42a0acc0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
